---
title: "Analysis_per_category"
author: "Miguel Alberto Pantoja-Zepeda"
date: "15/2/2023"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
load("~/Miguel_Github/MERS_CoV_analysis/processed_data/sex_assingned_data.RData")
joined_filtered_data <- improve_curation

```

# Library
```{r}
library("edgeR") # BiocManager::install("edgeR", update = FALSE)
library("ggplot2")
library("limma")
library("EnhancedVolcano")
library("pheatmap")
library("RColorBrewer")



```

# Functions

```{r,collapse=TRUE}
get_dge <- function(x){
  dge <- DGEList(
    counts = assay(x, "counts"),
    genes = rowData(x)
  )
  dge <- calcNormFactors(dge)
  dge
}

ggplot_genotype <- function(x){
  ggplot(as.data.frame(colData(x)), aes(y = assigned_gene_prop, x = genotype_factor)) +
    geom_boxplot() + geom_jitter(width=0.15,alpha=0.5)+
    theme_bw(base_size = 20) +
    ylab("Assigned Gene Prop") +
    xlab("Genotype Group")+
    scale_x_discrete(guide = guide_axis(n.dodge=3))
  
}

get_genotype_id <- function(x){
  unique(paste(x$genotype_factor,x$sra_attribute.genotype))

}


make_model_genotype <- function(x){
  mod <- model.matrix(~ sra_attribute.genotype +  sra_attribute.age + sra_attribute.tissue,
    data = colData(x)
)
  mod
}


get_de_results <- function(x, eb_results){
  de_results <- topTable(
    eb_results,
    coef = 2,
    number = nrow(x),
    sort.by = "none"
)
  de_results
}




make_volcano <- function(FC,p,de_results){
  keyvals <- rep('grey75', nrow(de_results))
  names(keyvals) <- rep('NS', nrow(de_results))
  
  keyvals[which(abs(de_results$logFC  ) > FC & de_results$P.Value > p)] <- 'grey50'
  names(keyvals)[which(abs(de_results$logFC) > FC & de_results$P.Value > p)] <- 'log2FoldChange'
  
  keyvals[which(abs(de_results$logFC  ) < FC & de_results$P.Value < p)] <- 'grey25'
  names(keyvals)[which(abs(de_results$logFC  ) < FC & de_results$P.Value < p)] <- '-Log10Q'
  
  keyvals[which(de_results$logFC < -FC & de_results$P.Value < p)] <- 'blue2'
  names(keyvals)[which(de_results$logFC  < -FC & de_results$P.Value < p)] <- 'Signif. down-regulated'
  
  keyvals[which(de_results$logFC > FC & de_results$P.Value < p)] <- 'red2'
  names(keyvals)[which(de_results$logFC > FC & de_results$P.Value < p)] <- 'Signif. up-regulated'
  
  unique(keyvals)
  unique(names(keyvals))
  
  EnhancedVolcano(de_results,
    lab = de_results$gene_name,
    x = 'logFC',
    y = 'adj.P.Val',
    title = 'Volcano plot',
    pCutoff = p,
    FCcutoff = FC,
    pointSize = 2.5,
    labSize = 4.5,
    colCustom = keyvals,
    colAlpha = 0.75,
    legendPosition = 'right',
    legendLabSize = 15,
    legendIconSize = 5.0,
    drawConnectors = TRUE,
    widthConnectors = 0.5,
    colConnectors = 'grey50',
    gridlines.major = TRUE,
    gridlines.minor = FALSE,
    border = 'partial')
}



make_MA_plot <- function(de_results, eb_results, p, FC){
  de_results.filt <- de_results[de_results$adj.P.Val < p,]  
  all_DEgenes <- de_results.filt[abs(de_results.filt$logFC)>FC,]
  
  DEgenes <- rownames(all_DEgenes) 
  limma::plotMA(eb_results, coef = 2, status = rownames(eb_results$lods) %in% DEgenes, legend = FALSE,
  main = "MA plot")
  legend("bottomright", c("DE genes", "Not DE genes"), fill = c("red", "black"), inset = 0.01)
}



make_heatmap <- function(x, exprs_heatmap ){
  
## Creemos una tabla con información de las muestras
## y con nombres de columnas más amigables
df <- as.data.frame(colData(x)[, c( "age_class","sra_attribute.genotype","sra_attribute.tissue")])
colnames(df) <- c( "Age", "Genotype", "Tissue")



## Hagamos un heatmap
pheatmap(
    exprs_heatmap,
    title='aaaah',
    cluster_rows = TRUE,
    cluster_cols = TRUE,
    show_rownames = TRUE,
    show_colnames = FALSE,
    annotation_col = df
)

pheatmap(
    exprs_heatmap,
    cluster_rows = TRUE,
    cluster_cols = TRUE,
    show_rownames = TRUE,
    show_colnames = FALSE,
    annotation_col = df,
    scale = "row"
)
df
}

```


# Analyze the WT vs others

## Genotype
```{r, message=FALSE}

joined_filtered_data$genotype_factor <- factor(joined_filtered_data$sra_attribute.genotype, levels=unique(joined_filtered_data$sra_attribute.genotype))
joined_filtered_data$genotype_factor <-factor( as.integer(joined_filtered_data$genotype_factor))

data_analyze <-  joined_filtered_data


dge <- get_dge(data_analyze)
ggplot_genotype(data_analyze)


```
```{r}
get_genotype_id(data_analyze)
```

```{r}

mod <- make_model_genotype(data_analyze)
#colnames(mod)
vGene <- voom(dge, mod, plot = TRUE)

```

```{r}


eb_results <- eBayes(lmFit(vGene))

de_results <- get_de_results(data_analyze, eb_results)
dim(de_results)
table(de_results$adj.P.Val < 0.05)


```


```{r}


FC <- 12
p <- 0.005

make_MA_plot(de_results, eb_results, p, FC)
```


```{r}

make_volcano(FC,p,de_results)

```



```{r}
## Extraer valores de los genes de interés
exprs_heatmap <- vGene$E[rank(de_results$adj.P.Val) <= 25, ]
rownames(exprs_heatmap) <-  de_results[rownames(exprs_heatmap),'gene_name']

## Creemos una tabla con información de las muestras
## y con nombres de columnas más amigables
df <- make_heatmap(data_analyze, exprs_heatmap)

```


# Analyze WT female vs other females

## Genotype
```{r}
data_analyze <- joined_filtered_data[,joined_filtered_data$Predicted_sex == 'female']

dge <- get_dge(data_analyze)

ggplot_genotype(data_analyze)
```
```{r}
get_genotype_id(data_analyze)

```


```{r}
mod <- make_model_genotype(data_analyze)

vGene <- voom(dge, mod, plot = TRUE)

eb_results <- eBayes(lmFit(vGene))

de_results <- get_de_results(data_analyze, eb_results)

dim(de_results)

table(de_results$adj.P.Val < 0.05)
```


```{r}

FC <- 2
p <- 0.05
make_MA_plot(de_results, eb_results, p, FC)

```


```{r}
make_volcano(FC,p,de_results)
```


```{r}
## Extraer valores de los genes de interés
exprs_heatmap <- vGene$E[rank(de_results$adj.P.Val) <= 25, ]
rownames(exprs_heatmap) <- de_results[rownames(exprs_heatmap),'gene_name']

df <- make_heatmap(data_analyze, exprs_heatmap)

```


# Analyze WT male vs other males

## Genotype
```{r}
data_analyze <- joined_filtered_data[,joined_filtered_data$Predicted_sex == 'male']

dge <- get_dge(data_analyze)

ggplot_genotype(data_analyze)
```
```{r}
get_genotype_id(data_analyze)

```


```{r}
mod <- make_model_genotype(data_analyze)

vGene <- voom(dge, mod, plot = TRUE)

eb_results <- eBayes(lmFit(vGene))

de_results <- get_de_results(data_analyze, eb_results)

dim(de_results)

table(de_results$adj.P.Val < 0.05)
```


```{r}
FC <- 12
p <- 0.05

make_MA_plot(de_results, eb_results, p, FC)
```


```{r}
make_volcano(FC,p,de_results)
```


```{r}
## Extraer valores de los genes de interés

exprs_heatmap <- vGene$E[rank(de_results$adj.P.Val) <= 25, ]
rownames(exprs_heatmap) <- de_results[rownames(exprs_heatmap),'gene_name']

df <- make_heatmap(data_analyze, exprs_heatmap)
```



```{r}
## Para colores

## Conviertiendo los grupos de edad a colores
col.group <- df$Age
levels(col.group) <- brewer.pal(nlevels(col.group), "Set1")

col.group <- as.character(col.group)

## MDS por grupos de edad
plotMDS(vGene$E, labels = df$Age, col = col.group)
```


```{r}
col.group <- df$Tissue
levels(col.group) <- brewer.pal(nlevels(col.group), "Set1")

col.group <- as.character(col.group)

## MDS por grupos de edad
plotMDS(vGene$E, labels = df$Tissue, col = col.group)
```


```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
